### ISSUE TITLE
batuannya

### ISSUE THREAD

**Issue by shoelyshtya** [AhmadMuzayyin/digitren#2]
bantuanya tutorial install di cpanel an di xampp

**Comment by AhmadMuzayyin** [comment]
Sementara boleh hubungi saya via WhatsApp, nanti saya update repository nya untuk tutorial install yang lebih

**Comment by AhmadMuzayyin** [comment]
Sementara boleh hubungi saya via WhatsApp, nanti saya update repository nya untuk tutorial install yang lebih
